Analysis Class Reference
Base class for analyses subclasses.
#include <analysis.h>
Public Member Functions
Analysis ()
Default Analysis constructor.
Analysis (Parameters &parameters, bool compare_groups, bool store_groups, bool store_sequence)
Standard Analysis constructor.
void print_starting_log ()
Print analysis starting log.
void print_groups ()
Print group counts.
void print_ending_log ()
Print analysis ending log.
void processor ()
Process batches of markers.
void run ()
Run the analysis.
virtual void extra_setup ()
Extra setup steps.
virtual void process_marker (Marker &)
Process a single marker.
virtual void generate_output ()
Generate output.
Public Attributes
std::chrono::steady_clock::time_point t_begin
Record analysis starting time.
Parameters parameters
Store RADSex parameters.
bool compare_groups
Flag indicating whether groups should be checked when loading the popmap.
bool store_groups
Flag indicating whether group info should be computed for each marker when parsing the markers table.
bool store_sequence
Flag indicating whether marker sequences should be stored for each marker when parsing the markers table.
Popmap popmap
Popmap instance storing group for each individual.
MarkersTable markers_table
Markers table instance implementing the markers table parser and markers queue.
std::thread parsing_thread
Markers table parsing thread.
std::thread processing_thread
Markers processing thread.
Detailed Description
Base class for analyses subclasses.
This class implements methods and attributes shared by all analyses:
Load parameters, load popmap, and initialize markers table parser in the constructor
Start markers table parsing thread and marker processing thread in run()
Read batches of markers from the markers queue in processor()
Three virtual methods are defined to implement analyses-specific behaviour:
extra_setup(): called at the beginning of run(), implement analysis-specific variables setup (e.g. BWA index in map function)
process_marker(): called for each marker obtained from the markers queue, implement what to do with a marker
generate_output(): called at the end of run(), implement generating output file when needed
Definition at line 48 of file analysis.h.
Constructor & Destructor Documentation
Analysis()
Analysis::Analysis (Parameters & parameters, bool compare_groups, bool store_groups, bool store_sequence)
Standard Analysis constructor.
Initialize MarkersTable instance, load parameters and popmap
Parameters
parameters Parameters object storing the value of all RADSex parameters
compare_groups If true, groups are checked when loading the popmap
store_groups If true, group info is computed for each marker when parsing the markers table
store_sequence If true, marker sequences are stored for each marker when parsing the markers table
Definition at line 28 of file analysis.cpp.
Member Function Documentation
extra_setup()
virtual void Analysis::extra_setup () [inline], [virtual]
Extra setup steps.
Function to be overloaded to implement extra setup steps required by an analysis, called at the beginning of run().
Reimplemented in Map, and Subset.
Definition at line 139 of file analysis.h.
Referenced by run().
generate_output()
virtual void Analysis::generate_output () [inline], [virtual]
Generate output.
Function to be overloaded to implement output file generation when required by an analysis, called at the end of run().
Reimplemented in Map, Depth, Signif, Distrib, and Freq.
Definition at line 157 of file analysis.h.
Referenced by run().
print_ending_log()
void Analysis::print_ending_log ()
Print analysis ending log.
Print ending log message with total runtime
Definition at line 67 of file analysis.cpp.
Referenced by run().
print_groups()
void Analysis::print_groups ()
Print group counts.
Print log message with group counts for groups compared by an analysis
Definition at line 57 of file analysis.cpp.
Referenced by print_starting_log().
print_starting_log()
void Analysis::print_starting_log ()
Print analysis starting log.
Print starting log message with the name of the analysis and group counts for analyses that make use of groups
Definition at line 46 of file analysis.cpp.
Referenced by run().
process_marker()
virtual void Analysis::process_marker (Marker &) [inline], [virtual]
Process a single marker.
Function to be overloaded to implement processing of a single marker in an analysis, called on each marker by processor().
Reimplemented in Map, Depth, Distrib, Signif, Subset, and Freq.
Definition at line 148 of file analysis.h.
Referenced by processor().
processor()
void Analysis::processor ()
Process batches of markers.
Get a batch of markers from the markers queue and call process_marker() on each marker.
Wait if queue is empty and update progress bar with processed markers.
Definition at line 97 of file analysis.cpp.
Referenced by run().
run()
void Analysis::run ()
Run the analysis.
Start the parsing and processing threads and print logs at start and end. Call extra_setup() and the start and generate_output() at the end.
Definition at line 77 of file analysis.cpp.
Referenced by main().
The documentation for this class was generated from the following files:
/home/romain/work/code/RadSex/src/analysis.h
/home/romain/work/code/RadSex/src/analysis.cpp