Marker Class Reference
Marker class.
#include <marker.h>
Public Member Functions
Marker ()
Default Marker constructor.
Marker (uint16_t n_individuals)
Standard Marker constructor.
void reset (bool sex_stats_only)
Reset a marker's attributes.
void output_as_table (std::ofstream &output_file) const
Output a marker in table format.
void output_as_fasta (std::ofstream &output_file, const uint min_depth) const
Output a marker in FASTA format.
Public Attributes
std::string id = ``
Marker ID (e.g. `5318835`)
std::string sequence = ``
Marker sequence.
std::vector< uint16_t > individual_depths
Vector storing marker depth in each individual (in order from the table's header)
std::unordered_map< std::string, uint > group_counts
Map storing group counts for the marker {group -> number of individuals in which the marker is present for this group}.
uint n_individuals = 0
Total number of individuals in which the marker is present.
float p = 0
P-value of association with group.
Detailed Description
Marker class.
Store information about a marker from the markers depth table and implement methods for parsing the markers depth table.
Definition at line 37 of file marker.h.
Constructor & Destructor Documentation
Marker()
Marker::Marker (uint16_t n_individuals)
Standard Marker constructor.
Initalized individual_depths size to n_individuals.
Parameters
n_individuals Number of individuals in the markers depth table
Definition at line 27 of file marker.cpp.
Member Function Documentation
output_as_fasta()
void Marker::output_as_fasta (std::ofstream & output_file, const uint min_depth) const
Output a marker in FASTA format.
Generate a FASTA header line with format `<id>_<group1:count>_<group2:count>_p:<p-value of association with group>_mindepth:<minimum depth to consider a marker present in the analysis` followed by the marker's sequence on a single line.
Parameters
output_file Output file stream
min_depth Minimum depth to consider a marker present in the current analysis
Definition at line 68 of file marker.cpp.
Referenced by Subset::process_marker().
output_as_table()
void Marker::output_as_table (std::ofstream & output_file) const
Output a marker in table format.
Generate a line with format: ID | Sequence | Depth in individual 1 | ... | Depth in individual N
Parameters
output_file Output file stream
Definition at line 56 of file marker.cpp.
Referenced by Subset::process_marker().
reset()
void Marker::reset (bool sex_stats_only)
Reset a marker's attributes.
Parameters
sex_stats_only If true, the marker ID and sequence won't be reset (save compute time when it's not needed)
Definition at line 37 of file marker.cpp.
Referenced by MarkersTable::start_parser().
The documentation for this class was generated from the following files:
/home/romain/work/code/RadSex/src/marker.h
/home/romain/work/code/RadSex/src/marker.cpp