Popmap Class Reference
Popmap class.
#include <popmap.h>
Public Member Functions
Popmap ()
Default Popmap constructor.
Popmap (Parameters &parameters, bool check_groups=false)
Standard Popmap constructor.
std::string get_group (const std::string &individual) const
Get group for an individual.
uint get_count (const std::string &group) const
Get individual count for a group.
std::string print_groups (const bool counts=false) const
Print all the groups in the popmap.
Public Attributes
uint16_t n_individuals = 0
Total number of individuals in the popmap.
Private Attributes
std::string file
Path to the popmap file.
std::unordered_map< std::string, std::string > individual_groups
Map storing group for each individual: {individual -> group}.
std::unordered_map< std::string, uint > group_counts
Map storing the number of individuals in each group: {group -> number of individuals}.
Detailed Description
Popmap class.
Store group information inferred from a tabulated file (popmap) and implement methods to get an individual's group and the number of individuals for a group.
Definition at line 36 of file popmap.h.
Constructor & Destructor Documentation
Popmap()
Popmap::Popmap (Parameters & parameters, bool check_groups = false)
Standard Popmap constructor.
Read a popmap file and store the group for each individual as well as individual counts for each group.
Parameters
parameters Parameters instance storing the value of all RADSex parameters
check_groups If true, performs checks on the groups obtained from the popmap
Definition at line 27 of file popmap.cpp.
Member Function Documentation
get_count()
uint Popmap::get_count (const std::string & group) const
Get individual count for a group.
Parameters
group Name of the group
Returns
The number of individuals for this group
Definition at line 117 of file popmap.cpp.
Referenced by Distrib::generate_output(), and Map::process_marker().
get_group()
std::string Popmap::get_group (const std::string & individual) const
Get group for an individual.
Parameters
individual Name of the individual
Returns
A string containing the group for the individual or `` if the individual was not in the popmap
Definition at line 96 of file popmap.cpp.
Referenced by Depth::generate_output().
print_groups()
std::string Popmap::print_groups (const bool counts = false) const
Print all the groups in the popmap.
Parameters
counts If true, counts are printed along groups (e.g. `Group1: 15, Group2: 20`)
Returns
A string with comma-separated groups (e.g. `Group1, Group2`)
Definition at line 138 of file popmap.cpp.
Referenced by Popmap().
The documentation for this class was generated from the following files:
/home/romain/work/code/RadSex/src/popmap.h
/home/romain/work/code/RadSex/src/popmap.cpp