MarkersTable Class Reference
MarkersTable class.
#include <markers_table.h>
Public Member Functions
MarkersTable ()
Default MarkersTable constructor.
MarkersTable (Parameters *parameters)
Standard MarkersTable constructor.
void start_parser (bool store_sequence=true, bool compute_groups=true)
Read markers from a markers depth table and store them in a queue.
void get_batch (std::vector< Marker > &batch)
Get a batch of markers from the queue.
void set_popmap (Popmap *popmap)
Set the popmap attribute value.
Public Attributes
Header header
Header instance storing information about the markers table.
std::queue< Marker > markers_queue
Queue of Marker objects to be processed in an analysis.
uint64_t n_markers_processed = 0
Total number of markers loaded from the markers table.
std::mutex mutex
Mutex to protect the markers queue when pushing / reading batches of markers.
bool parsing_ended = false
Flag indicating whether parsing of the markers table ended.
std::vector< std::string > groups
Vector storing the group (obtained from the popmap) for each individual based on column indices.
Private Member Functions
void get_group_columns ()
Get group for each column in the markers table.
Private Attributes
Parameters * parameters
Pointer to a Parameters instance storing all RADSex parameters.
Popmap * popmap
Pointer to a popmap instance storing group for each individual.
Detailed Description
MarkersTable class.
This class stores information about a markers table file and implements two methods:
start_parser(): parse the markers table and store each marker in a queue of Marker objects
get_batch(): get a batch of markers from the Marker queue to be processed in an analysis
These methods are implemented to be run on two concurrent threads (one thread each).
Definition at line 84 of file markers_table.h.
Constructor & Destructor Documentation
MarkersTable()
MarkersTable::MarkersTable (Parameters * parameters)
Standard MarkersTable constructor.
Initialize parameters and read the markers table header
Parameters
parameters Pointer to a Parameter object storing all RADSex parameter values
Definition at line 58 of file markers_table.cpp.
Member Function Documentation
get_batch()
void MarkersTable::get_batch (std::vector< Marker > & batch)
Get a batch of markers from the queue.
Read a batch of markers of size BATCH_SIZE and store it in the Markers vector batch.
Parameters
batch Vector of Marker objects storing the current markers batch
Definition at line 211 of file markers_table.cpp.
Referenced by Analysis::processor().
get_group_columns()
void MarkersTable::get_group_columns () [private]
Get group for each column in the markers table.
Create a vector of groups to easily access a column's groups by index.
Definition at line 237 of file markers_table.cpp.
Referenced by start_parser().
set_popmap()
void MarkersTable::set_popmap (Popmap * popmap)
Set the popmap attribute value.
Usually, the popmap is not yet loaded when the MarkersTable instance is created. This method is used to set the pointer to the Popmap object after loading the popmap.
Parameters
popmap Pointer to a Popmap object
Definition at line 248 of file markers_table.cpp.
Referenced by Analysis::Analysis().
start_parser()
void MarkersTable::start_parser (bool store_sequence = true, bool compute_groups = true)
Read markers from a markers depth table and store them in a queue.
Read a markers depth table generated with process(). Each marker is stored in a Marker instance which is pushed to a queue. The function waits if the queue gets bigger than MAX_QUEUE_SIZE. Batches of markers are obtained from the queue with get_batch().
Parameters
store_sequence If true, marker sequences and IDs are be stored in Marker objects
compute_groups If true, group counts are computed for each marker
Definition at line 70 of file markers_table.cpp.
Referenced by Analysis::run().
The documentation for this class was generated from the following files:
/home/romain/work/code/RadSex/src/markers_table.h
/home/romain/work/code/RadSex/src/markers_table.cpp