/home/romain/work/code/RadSex/src/process.cpp File Reference
Implements functions for the `process` command.
#include `process.h`
Functions
KSEQ_INIT (gzFile, gzread)
Macro to initalize reading sequences from file with Kseq.
std::vector< InputFile > get_input_files (const std::string &input_dir_path)
Get input files.
void process (Parameters &parameters)
Main function implementing the `process` command.
void file_processor (std::vector< InputFile > &input_files, std::unordered_map< std::string, std::unordered_map< std::string, uint16_t >> &results, std::mutex &results_mutex, std::mutex &files_mutex)
File processor.
void process_file (InputFile &input_file, std::unordered_map< std::string, std::unordered_map< std::string, uint16_t >> &results, std::mutex &results_mutex)
Process a single file.
Detailed Description
Implements functions for the `process` command.
Function Documentation
file_processor()
void file_processor (std::vector< InputFile > & input_files, std::unordered_map< std::string, std::unordered_map< std::string, uint16_t >> & results, std::mutex & results_mutex, std::mutex & files_mutex) [inline]
File processor.
Look for an unprocessed input file in the vector of input files generated by get_input_files() and process this file.
Parameters
input_files Vector of InputFile generated by get_input_files()
results A map of marker depth for each individual: {Marker -> {Individual -> depth}}
results_mutex A mutex protecting the marker depth map when writing from process_file()
files_mutex A mutex to lock the InputFile vector while looking for a file to process
Definition at line 173 of file process.cpp.
Referenced by process().
get_input_files()
std::vector<InputFile> get_input_files (const std::string & input_dir_path)
Get input files.
Detect all input files in the input directory based on extensions and store file information in a InputFile vector.
Parameters
input_dir_path Path to the input directory
Returns
A vector of InputFile objects, each containing information about an input file
Definition at line 28 of file process.cpp.
Referenced by process().
process()
void process (Parameters & parameters)
Main function implementing the `process` command.
Generate a markers depth table from all individual reads files detected in an input directory. The function spans multiple file_processor() threads to process input files in parallel.
Parameters
parameters A Parameters object storing the value of all RADSex parameters
Definition at line 97 of file process.cpp.
Referenced by main(), and parse_args().
process_file()
void process_file (InputFile & input_file, std::unordered_map< std::string, std::unordered_map< std::string, uint16_t >> & results, std::mutex & results_mutex) [inline]
Process a single file.
Read all sequences from an input file with kseq_read() and increment the marker depth table accordingly.
Parameters
input_file Path to the reads file
results A map of marker depth for each individual: {Marker -> {Individual -> depth}}
results_mutex A mutex protecting the marker depth map when writing from multiple processing threads
Definition at line 213 of file process.cpp.
Referenced by file_processor().