/home/romain/work/code/RadSex/src/stats.h File Reference
Defines functions to compute statistical tests and p-values.
#include `kfun/kfun.h`
#include `utils.h`
Functions
double get_chi_squared (uint n_group1, uint n_group2, uint total_group1, uint total_group2)
Compute Chi-squared.
double get_chi_squared_p (double chi_squared)
Get P-value for a Chi-squared test.
double get_p_association (uint n_group1, uint n_group2, uint total_group1, uint total_group2)
Compute the p-value of association with group with a Chi-squared test.
template<typename T >
T find_median (std::vector< T > &container)
Find median value for a vector.
Detailed Description
Defines functions to compute statistical tests and p-values.
Function Documentation
find_median()
template<typename T >
T find_median (std::vector< T > & container)
Find median value for a vector.
Parameters
container Vector of values
Returns
Median value in the vector
Definition at line 78 of file stats.h.
Referenced by Depth::generate_output().
get_chi_squared()
double get_chi_squared (uint n_group1, uint n_group2, uint total_group1, uint total_group2)
Compute Chi-squared.
Parameters
n_group1 Number of individuals in the first group
n_group2 Number of individuals in the second group
total_group1 Total number of individuals in the first group
total_group2 Total number of individuals in the second group
Returns
Definition at line 41 of file stats.cpp.
Referenced by get_p_association().
get_chi_squared_p()
double get_chi_squared_p (double chi_squared)
Get P-value for a Chi-squared test.
Parameters
chi_squared Chi-squared value obtained with get_chi_squared()
Returns
The p-value associated with chi_squared
Definition at line 26 of file stats.cpp.
Referenced by get_p_association().
get_p_association()
double get_p_association (uint n_group1, uint n_group2, uint total_group1, uint total_group2)
Compute the p-value of association with group with a Chi-squared test.
Parameters
n_group1 Number of individuals in the first group
n_group2 Number of individuals in the second group
total_group1 Total number of individuals in the first group
total_group2 Total number of individuals in the second group
Returns
Definition at line 65 of file stats.cpp.
Referenced by Distrib::generate_output(), Subset::process_marker(), Signif::process_marker(), and Map::process_marker().