/home/romain/work/code/RadSex/src/utils.h File Reference
Implements general utility functions used.
#include <algorithm>
#include <chrono>
#include <cmath>
#include <fstream>
#include <iostream>
#include <map>
#include <string>
#include <thread>
#include <time.h>
#include <unordered_map>
#include <vector>
Macros
#define TIME_FORMAT `%Y-%m-%d %H:%M:%S`
Date and time format for logging.
#define MAX_TIME_SIZE 21
Max number of characters in TIME_FORMAT.
#define LOG_ERROR `ERROR`
Message prefix for log level ERROR.
#define LOG_WARNING `WARNING`
Message prefix for log level WARNING.
#define LOG_INFO `INFO`
Message prefix for log level INFO.
Functions
char * print_time (char *buff)
Print current time.
std::vector< std::string > split (std::string str, const std::string &separator=`\t`)
Split a string into a vector of string.
int fast_stoi (const char *str)
Fast stoi conversion.
template<typename T >
void log (T line, const std::string level=LOG_INFO, bool flushline=true)
Print logging message.
std::ifstream open_input (const std::string &input_file_path)
Open an input file and check that the file is open properly.
std::ofstream open_output (const std::string &output_file_path)
Open an output file and check that the file is open properly.
void log_progress (uint64_t &n_processed_markers, const uint32_t marker_processed_tick)
Print a progress log message.
std::string get_runtime (const std::chrono::steady_clock::time_point t_begin)
Compute runtime until present time.
void log_progress_bar (uint64_t &n_processed_markers, const uint32_t marker_processed_tick, char symbol='#', uint16_t ticks=50)
Update a progress bar log message.
template<typename T >
std::string print_list (const T &list, const std::string &sep=`, `)
Print a container as a `sep`-separated string.
Detailed Description
Implements general utility functions used.
Function Documentation
fast_stoi()
int fast_stoi (const char * str) [inline]
Fast stoi conversion.
I honestly don't know how it works but it's fast.
Parameters
str Pointer to a char array to convert to int
Returns
The converted string as an int
Definition at line 103 of file utils.h.
Referenced by MarkersTable::start_parser().
get_runtime()
std::string get_runtime (const std::chrono::steady_clock::time_point t_begin) [inline]
Compute runtime until present time.
Parameters
t_begin Time point at the start of a measurement
Returns
Runtime until now as a string with format `<H>h <M>m <S>s`
Definition at line 222 of file utils.h.
Referenced by Analysis::print_ending_log(), and process().
log()
template<typename T >
void log (T line, const std::string level = LOG_INFO, bool flushline = true) [inline]
Print logging message.
Parameters
line Message to print
level Log level, either LOG_INFO, LOG_WARNING, or LOG_ERROR
flushline If true, std::endl is added at the end of the log line
Definition at line 127 of file utils.h.
Referenced by Popmap::get_count(), Popmap::get_group(), get_input_files(), Header::Header(), Map::load_bwa_index(), log_progress(), log_progress_bar(), open_input(), open_output(), Popmap::Popmap(), Analysis::print_ending_log(), Analysis::print_groups(), Analysis::print_starting_log(), process(), process_file(), and MarkersTable::start_parser().
log_progress()
void log_progress (uint64_t & n_processed_markers, const uint32_t marker_processed_tick) [inline]
Print a progress log message.
Parameters
n_processed_markers Number of markers processed
marker_processed_tick Number of markers corresponding to 1% of total markers
Definition at line 201 of file utils.h.
log_progress_bar()
void log_progress_bar (uint64_t & n_processed_markers, const uint32_t marker_processed_tick, char symbol = '#', uint16_t ticks = 50) [inline]
Update a progress bar log message.
Parameters
n_processed_markers Number of markers processed
marker_processed_tick Number of markers corresponding to 1% of total markers
symbol Symbol to use to draw the progress bar (e.g. # -> [###...])
ticks Total number of ticks in progress bar (should be a factor of 100)
Definition at line 246 of file utils.h.
Referenced by process(), and Analysis::processor().
open_input()
std::ifstream open_input (const std::string & input_file_path) [inline]
Open an input file and check that the file is open properly.
Parameters
input_file_path Path to the file to open
Returns
An input file stream for the input file
Definition at line 148 of file utils.h.
Referenced by Map::load_contig_lengths(), Popmap::Popmap(), and MarkersTable::start_parser().
open_output()
std::ofstream open_output (const std::string & output_file_path) [inline]
Open an output file and check that the file is open properly.
Parameters
output_file_path Path to the file to open
Returns
An output file stream for the output file
Definition at line 175 of file utils.h.
Referenced by Subset::extra_setup(), Map::extra_setup(), Freq::generate_output(), Distrib::generate_output(), Signif::generate_output(), Depth::generate_output(), and process().
print_list()
template<typename T >
std::string print_list (const T & list, const std::string & sep = `, `) [inline]
Print a container as a `sep`-separated string.
Parameters
list Container to print
sep Separator between container elements
Returns
A string of all items in the container separated by sep.
Definition at line 281 of file utils.h.
Referenced by Subset::extra_setup(), and Signif::generate_output().
print_time()
char* print_time (char * buff) [inline]
Print current time.
Parameters
buff Char array to store current time
Returns
Formatted current time as a char array
Definition at line 52 of file utils.h.
Referenced by log().
split()
std::vector<std::string> split (std::string str, const std::string & separator = `\t`) [inline]
Split a string into a vector of string.
Parameters
str The string to split
separator Separator to split the string by
Returns
The splitted string as vector of strings
Definition at line 73 of file utils.h.
Referenced by get_input_files(), Header::Header(), Map::load_contig_lengths(), CustomFormatter::make_option(), and Popmap::Popmap().