#include "subset.h"


void subset(Parameters& parameters) {

    /* The subset function parses through a file generated by process_reads and outputs sequences with the following criteria:
     * - Found in M males with min_males <= M <= max_males
     * - Found in F females with min_females <= F <= max_females
     */

    std::unordered_map<std::string, bool> popmap = load_popmap(parameters);

    uint n_males_total = 0, n_females_total = 0;
    for (auto i: popmap) if (i.second) ++n_males_total; else ++n_females_total;

    if (parameters.set_max_males) parameters.subset_max_males = n_males_total;
    if (parameters.set_max_females) parameters.subset_max_females = n_females_total;
    if (parameters.set_max_individuals) parameters.subset_max_individuals= n_males_total + n_females_total;

    std::ifstream input_file;
    input_file.open(parameters.markers_table_path);

    if (input_file) {

        std::ofstream output_file;
        output_file.open(parameters.output_file_path);

        std::vector<std::string> line;
        std::string temp = "";

        // First line is a comment with number of markers in the table
        std::getline(input_file, temp);
        line = split(temp, " : ");
        if (line.size() == 2) uint n_markers = static_cast<uint>(std::stoi(line[1]));

        // Second line is the header. The header is parsed to get the sex of each field in the table.
        std::getline(input_file, temp);
        line = split(temp, "\t");
        if (not parameters.output_fasta) output_file << temp << "\n"; // Copy the header line to the output file

        // Map with column number --> index of sex_count (0 = male, 1 = female, 2 = no sex)
        std::unordered_map<uint, uint> sex_columns = get_column_sex(popmap, line);

        // Define variables used to read the file
        char buffer[65536];
        std::string temp_line;
        uint k = 0, field_n = 0;
        uint sex_count[3] = {0, 0, 0}; // Index: 0 = male, 1 = female, 2 = no sex
        uint n_individuals = 0;

        do {

            // Read a chunk of size given by the buffer
            input_file.read(buffer, sizeof(buffer));
            k = static_cast<uint>(input_file.gcount());

            for (uint i=0; i<k; ++i) {

                // Read the buffer character by character
                switch(buffer[i]) {

                    case '\t':  // New field
                        if (sex_columns[field_n] != 2 and static_cast<uint>(std::stoi(temp)) >= parameters.min_depth) ++sex_count[sex_columns[field_n]];  // Increment the appropriate counter
                        temp = "";
                        temp_line += buffer[i];
                        ++field_n;
                        break;

                    case '\n':  // New line (also a new field)
                        if (sex_columns[field_n] != 2 and static_cast<uint>(std::stoi(temp)) >= parameters.min_depth) ++sex_count[sex_columns[field_n]];  // Increment the appropriate counter
                        n_individuals = sex_count[0] + sex_count[1] + sex_count[2];
                        if (sex_count[0] >= parameters.subset_min_males and sex_count[0] <= parameters.subset_max_males and
                            sex_count[1] >= parameters.subset_min_females and sex_count[1] <= parameters.subset_max_females and
                            n_individuals >= parameters.subset_min_individuals and n_individuals <= parameters.subset_max_individuals) {
                            if (parameters.output_fasta) {
                                line = split(temp_line, "\t");
                                output_file << ">" << line[0] << "_" << sex_count[0] << "M_" << sex_count[1] << "F_mindepth:" << parameters.min_depth << "\n" << line[1] << "\n";
                            } else {
                                output_file << temp_line << "\n";
                            }
                        }
                        // Reset variables
                        temp = "";
                        temp_line = "";
                        field_n = 0;
                        sex_count[0] = 0;
                        sex_count[1] = 0;
                        break;

                    default:
                        temp += buffer[i];
                        temp_line += buffer[i];
                        break;
                }
            }

        } while (input_file);

        output_file.close();
        input_file.close();
    }
}
